import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { DarkContextProvider } from '@/Context/Buttontoggle'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DarkContextProvider>
        {children}
        </DarkContextProvider>
        </body>
    </html>
  )
}
